; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32s3-1_16_8
board_build.variants_dir = variants
framework = arduino
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DconfigUSE_TRACE_FACILITY=1
	-DconfigGENERATE_RUN_TIME_STATS=1
board_build.filesystem = littlefs
lib_deps = 
	gilmaimon/ArduinoWebsockets@^0.5.4
	esphome/ESP32-audioI2S@^2.0.7
	bblanchon/ArduinoJson@^7.3.1
